package org.processmining.earthmoversstochasticconformancechecking.stochasticalignment;

public class StochasticTraceAlignmentsParametersLogLogDefault extends StochasticTraceAlignmentsParametersLogLogAbstract {

}
